baseurl = "/"
title = "StolpSys.com"
copyright = "Copyright StolpSyS.com (c) 2024, all rights reserved."
canonifyurls = true
languageCode = "en-US"
pagination.pagerSize = 3
theme = "hugo-dusk"
contentDir = "content"

googleAnalytics = ""
disqusShortname = ""

[params.author]
  name = "jstolp"

SectionPagesMenu = "main"

# Configure syntax highlight
[markup]
  [markup.highlight]
    style = "gruvbox"  # dark themes: monokai, api, fruity, native, rrt, swapoff ... https://xyproto.github.io/splash/docs/longer/all.html

[[menu.main]]
  name = "Posts"
  weight = -120
  identifier = "posts"
  url = "/posts/"

[[menu.main]]
  name = "Tags"
  weight = -110
  identifier = "tag"
  url = "/tags/"

[params.meta]
  keywords = "blog, tech"
  description = "Personal StolpSyS Development blog."

[params]
  github = "jstolp"
  linkedin = "jeroen-stolp-86243a11"
  email = "webmaster@stolpsys.com"
  theme_colors = "default-dark" # uses color css file under static/css/default-dark.css
  utterancesRepo="REPO_NAME" # Utterances is enabled when this param is set
  utterancesTheme="github-dark" # Default: github-dark
  utterancesIssueTerm="pathname" # Default: pathname